/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedEmpresasRouteImport } from './routes/_authenticated/empresas'
import { Route as AuthenticatedEmailsNaoVinculadosRouteImport } from './routes/_authenticated/emails-nao-vinculados'
import { Route as AuthenticatedEditaisRouteImport } from './routes/_authenticated/editais'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCronogramaRouteImport } from './routes/_authenticated/cronograma'
import { Route as AuthenticatedProjetosIndexRouteImport } from './routes/_authenticated/projetos.index'
import { Route as ApiPublicInboundEmailRouteImport } from './routes/api/public/inbound-email'
import { Route as AuthenticatedProjetosIdRouteImport } from './routes/_authenticated/projetos.$id'
import { Route as AuthenticatedEmpresasIdRouteImport } from './routes/_authenticated/empresas.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresasRoute = AuthenticatedEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailsNaoVinculadosRoute =
  AuthenticatedEmailsNaoVinculadosRouteImport.update({
    id: '/emails-nao-vinculados',
    path: '/emails-nao-vinculados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEditaisRoute = AuthenticatedEditaisRouteImport.update({
  id: '/editais',
  path: '/editais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCronogramaRoute = AuthenticatedCronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjetosIndexRoute =
  AuthenticatedProjetosIndexRouteImport.update({
    id: '/projetos/',
    path: '/projetos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicInboundEmailRoute = ApiPublicInboundEmailRouteImport.update({
  id: '/api/public/inbound-email',
  path: '/api/public/inbound-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjetosIdRoute = AuthenticatedProjetosIdRouteImport.update({
  id: '/projetos/$id',
  path: '/projetos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresasIdRoute = AuthenticatedEmpresasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedEmpresasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cronograma': typeof AuthenticatedCronogramaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/editais': typeof AuthenticatedEditaisRoute
  '/emails-nao-vinculados': typeof AuthenticatedEmailsNaoVinculadosRoute
  '/empresas': typeof AuthenticatedEmpresasRouteWithChildren
  '/insights': typeof AuthenticatedInsightsRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/empresas/$id': typeof AuthenticatedEmpresasIdRoute
  '/projetos/$id': typeof AuthenticatedProjetosIdRoute
  '/api/public/inbound-email': typeof ApiPublicInboundEmailRoute
  '/projetos/': typeof AuthenticatedProjetosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cronograma': typeof AuthenticatedCronogramaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/editais': typeof AuthenticatedEditaisRoute
  '/emails-nao-vinculados': typeof AuthenticatedEmailsNaoVinculadosRoute
  '/empresas': typeof AuthenticatedEmpresasRouteWithChildren
  '/insights': typeof AuthenticatedInsightsRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/empresas/$id': typeof AuthenticatedEmpresasIdRoute
  '/projetos/$id': typeof AuthenticatedProjetosIdRoute
  '/api/public/inbound-email': typeof ApiPublicInboundEmailRoute
  '/projetos': typeof AuthenticatedProjetosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/cronograma': typeof AuthenticatedCronogramaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/editais': typeof AuthenticatedEditaisRoute
  '/_authenticated/emails-nao-vinculados': typeof AuthenticatedEmailsNaoVinculadosRoute
  '/_authenticated/empresas': typeof AuthenticatedEmpresasRouteWithChildren
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/empresas/$id': typeof AuthenticatedEmpresasIdRoute
  '/_authenticated/projetos/$id': typeof AuthenticatedProjetosIdRoute
  '/api/public/inbound-email': typeof ApiPublicInboundEmailRoute
  '/_authenticated/projetos/': typeof AuthenticatedProjetosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cronograma'
    | '/dashboard'
    | '/editais'
    | '/emails-nao-vinculados'
    | '/empresas'
    | '/insights'
    | '/usuarios'
    | '/empresas/$id'
    | '/projetos/$id'
    | '/api/public/inbound-email'
    | '/projetos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cronograma'
    | '/dashboard'
    | '/editais'
    | '/emails-nao-vinculados'
    | '/empresas'
    | '/insights'
    | '/usuarios'
    | '/empresas/$id'
    | '/projetos/$id'
    | '/api/public/inbound-email'
    | '/projetos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/cronograma'
    | '/_authenticated/dashboard'
    | '/_authenticated/editais'
    | '/_authenticated/emails-nao-vinculados'
    | '/_authenticated/empresas'
    | '/_authenticated/insights'
    | '/_authenticated/usuarios'
    | '/_authenticated/empresas/$id'
    | '/_authenticated/projetos/$id'
    | '/api/public/inbound-email'
    | '/_authenticated/projetos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicInboundEmailRoute: typeof ApiPublicInboundEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresas': {
      id: '/_authenticated/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthenticatedEmpresasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emails-nao-vinculados': {
      id: '/_authenticated/emails-nao-vinculados'
      path: '/emails-nao-vinculados'
      fullPath: '/emails-nao-vinculados'
      preLoaderRoute: typeof AuthenticatedEmailsNaoVinculadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/editais': {
      id: '/_authenticated/editais'
      path: '/editais'
      fullPath: '/editais'
      preLoaderRoute: typeof AuthenticatedEditaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cronograma': {
      id: '/_authenticated/cronograma'
      path: '/cronograma'
      fullPath: '/cronograma'
      preLoaderRoute: typeof AuthenticatedCronogramaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projetos/': {
      id: '/_authenticated/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof AuthenticatedProjetosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/inbound-email': {
      id: '/api/public/inbound-email'
      path: '/api/public/inbound-email'
      fullPath: '/api/public/inbound-email'
      preLoaderRoute: typeof ApiPublicInboundEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projetos/$id': {
      id: '/_authenticated/projetos/$id'
      path: '/projetos/$id'
      fullPath: '/projetos/$id'
      preLoaderRoute: typeof AuthenticatedProjetosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresas/$id': {
      id: '/_authenticated/empresas/$id'
      path: '/$id'
      fullPath: '/empresas/$id'
      preLoaderRoute: typeof AuthenticatedEmpresasIdRouteImport
      parentRoute: typeof AuthenticatedEmpresasRoute
    }
  }
}

interface AuthenticatedEmpresasRouteChildren {
  AuthenticatedEmpresasIdRoute: typeof AuthenticatedEmpresasIdRoute
}

const AuthenticatedEmpresasRouteChildren: AuthenticatedEmpresasRouteChildren = {
  AuthenticatedEmpresasIdRoute: AuthenticatedEmpresasIdRoute,
}

const AuthenticatedEmpresasRouteWithChildren =
  AuthenticatedEmpresasRoute._addFileChildren(
    AuthenticatedEmpresasRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCronogramaRoute: typeof AuthenticatedCronogramaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEditaisRoute: typeof AuthenticatedEditaisRoute
  AuthenticatedEmailsNaoVinculadosRoute: typeof AuthenticatedEmailsNaoVinculadosRoute
  AuthenticatedEmpresasRoute: typeof AuthenticatedEmpresasRouteWithChildren
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedProjetosIdRoute: typeof AuthenticatedProjetosIdRoute
  AuthenticatedProjetosIndexRoute: typeof AuthenticatedProjetosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCronogramaRoute: AuthenticatedCronogramaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEditaisRoute: AuthenticatedEditaisRoute,
  AuthenticatedEmailsNaoVinculadosRoute: AuthenticatedEmailsNaoVinculadosRoute,
  AuthenticatedEmpresasRoute: AuthenticatedEmpresasRouteWithChildren,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedProjetosIdRoute: AuthenticatedProjetosIdRoute,
  AuthenticatedProjetosIndexRoute: AuthenticatedProjetosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicInboundEmailRoute: ApiPublicInboundEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
